# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.1
#   kernelspec:
#     display_name: dolfinx-env
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Time-Dependent Coupling Depth Subduction Zone Setup

# %% [markdown]
# ## Preamble
#
# Let's start by adding the path to the modules in the `python` folder to the system path (so we can find the our custom modules).

# %%
import sys, os, shutil
basedir = ''
if "__file__" in globals(): basedir = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(basedir, os.path.pardir, os.path.pardir, 'python'))

# %% [markdown]
# Let's also load the module generated by the previous notebooks to get access to the parameters and functions defined there.

# %%
from fenics_sz.sz_problems.sz_problem import StokesSolverNest, TemperatureSolver
from fenics_sz.sz_problems.sz_tdep_dislcreep import TDDislSubductionProblem

# %% [markdown]
# Then let's load all the required modules at the beginning.

# %%
import dolfinx as df
import numpy as np
import scipy as sp
import pathlib
output_folder = pathlib.Path(os.path.join(basedir, "output"))
output_folder.mkdir(exist_ok=True, parents=True)


# %%
class TDCDDislSubductionProblem(TDDislSubductionProblem):
    def members(self):
        # initialize the standard members in the parent class
        super().members()

        # add additional parameter for time-dependent coupling
        self.allowed_input_parameters += ["cd0", "cdf", "dcd", "tc0", "tcf"]
        self.required_parameters += ["cd0", "cdf", "dcd", "tc0", "tcf"]
        self.required_parameters += ["As"] # this was previously only required if oceanic

        self.cd0 = None # initial coupling depth
        self.cdf = None # final coupling depth
        self.dcd = None # partial coupling depth offset
        self.tc0 = None # time for initial coupling (in Myr)
        self.tcf = None # time for full coupling (in Myr)

        self.t_Myr = 0.0 # current dimensional time (in Myr)
        self.tdep_bcs = ['vw_slabtop'] # one time-dependet boundary condition

    # Overload the vw_slabtop method
    def vw_slabtop(self, x):
        """
        Return the wedge velocity on the slab surface
        """
        # work out the current coupling depth from the time
        # FIXME: this really should be stored
        cd = min(max(self.cd0, self.cd0 + (self.cdf - self.cd0)/(self.tcf - self.tc0)*(self.t_Myr - self.tc0)), self.cdf)
        pcd = cd - self.dcd # current partial coupling depth
        v = np.empty((self.gdim, x.shape[1]))
        for i in range(x.shape[1]):
            v[:,i] = min(max(-(x[1,i]+pcd)/self.dcd, 0.0), 1.0)*self.Vs_nd*self.geom.slab_spline.unittangentx(x[0,i])
        return v
    
    def T_trench(self, x):
        """
        Return temperature at the trench
        """
        zd = 2*np.sqrt(self.kappa0*self.A_si)/self.h0  # incoming slab scale depth (non-dim)
        deltazsurface = np.minimum(np.maximum(self.deltaztrench*(1.0 - x[0,:]/max(self.deltaxcoast, np.finfo(float).eps)), 0.0), self.deltaztrench)
        return self.Ts + (self.Tm-self.Ts)*sp.special.erf(-(x[1,:]+deltazsurface)/zd)


# %%

# %% [markdown]
# ## 43 Izu example with a time-dependent coupling depth

# %% [markdown]
# ### Preamble

# %% [markdown]
# Set some path information.

# %% [markdown]
# Loading everything we need from `sz_problem` and also set our default plotting and output preferences.

# %%
import fenics_sz.utils
from fenics_sz.sz_problems.sz_params import allsz_params, default_params
from fenics_sz.sz_problems.sz_slab import create_slab, plot_slab
from fenics_sz.sz_problems.sz_geometry import create_sz_geometry
import numpy as np
import dolfinx as df
import pyvista as pv
import pathlib
import copy
import matplotlib.pyplot as pl
output_folder = pathlib.Path(os.path.join(basedir, "output"))
output_folder.mkdir(exist_ok=True, parents=True)

# %% [markdown]
# ### Parameters

# %% [markdown]
# We first select the name and resolution scale, `resscale` and target Courant number `cfl` of the model.
#
# ```{admonition} Resolution
# By default the resolution (both spatial and temporal) is low to allow for a quick runtime and smaller website size.  If sufficient computational resources are available set a lower `resscale` and a lower `cfl` to get higher spatial and temporal resolutions respectively. This is necessary to get results with sufficient accuracy for scientific interpretation.
# ```
#

# %%
name = "43_Izu"
resscale = 3.0
cfl      = 3.0

# %% [markdown]
# Then load the remaining parameters from the global suite.

# %%
szdict = allsz_params[name]
print("{}:".format(name))
print("{:<20} {:<10}".format('Key','Value'))
print("-"*85)
for k, v in allsz_params[name].items():
    if v is not None and k not in ['z0', 'z15']: print("{:<20} {}".format(k, v))

# %% [markdown]
# Modify the age of subduction to 52 Myr:

# %%
szdict['As'] = 52.0

# %% [markdown]
# ### Setup

# %% [markdown]
# Setup a slab.

# %%
slab = create_slab(szdict['xs'], szdict['ys'], resscale, szdict['lc_depth'])
_ = plot_slab(slab)

# %% [markdown]
# Create the subduction zome geometry around the slab.

# %%
geom = create_sz_geometry(slab, resscale, szdict['sztype'], szdict['io_depth'], szdict['extra_width'], 
                             szdict['coast_distance'], szdict['lc_depth'], szdict['uc_depth'])
_ = geom.plot()

# %% [markdown]
# Finally, declare the `TDDislSubductionProblem` problem class using the dictionary of parameters.

# %%
sz = TDCDDislSubductionProblem(geom, **szdict, 
                               cd0=30, cdf=80, dcd=default_params['coupling_depth_range'],
                               tc0=0.0, tcf=szdict['As'])

# %% [markdown]
# ### Solve

# %% [markdown]
# Solve using a dislocation creep rheology.

# %%
# save period
save_period = 1.0

# Select the timestep based on the approximate target Courant number
dt = cfl*resscale/szdict['Vs']
# Reduce the timestep to get an integer number of timesteps per save period
dt = save_period/np.ceil(save_period/dt)

solutions = sz.solve(szdict['As'], dt, theta=0.5, rtol=1.e-1, verbosity=2, save_period=save_period)

# %% [markdown]
# ### Plot

# %% [markdown]
# Plot the solution at the finish time.

# %%
plotter = pv.Plotter()
fenics_sz.utils.plot.plot_scalar(sz.T_i, plotter=plotter, scale=sz.T0, gather=True, cmap='coolwarm', scalar_bar_args={'title': 'Temperature (deg C)', 'bold':True})
fenics_sz.utils.plot.plot_vector_glyphs(sz.vw_i, plotter=plotter, gather=True, factor=0.1, color='k', scale=fenics_sz.utils.mps_to_mmpyr(sz.v0))
fenics_sz.utils.plot.plot_vector_glyphs(sz.vs_i, plotter=plotter, gather=True, factor=0.1, color='k', scale=fenics_sz.utils.mps_to_mmpyr(sz.v0))
geom.pyvistaplot(plotter=plotter, color='green', width=2)
cdpt = slab.findpoint('Slab::FullCouplingDepth')
fenics_sz.utils.plot.plot_points([[cdpt.x, cdpt.y, 0.0]], plotter=plotter, render_points_as_spheres=True, point_size=10.0, color='green')
fenics_sz.utils.plot.plot_show(plotter)
fenics_sz.utils.plot.plot_save(plotter, output_folder / "{}_td_solution_resscale_{:.2f}_cfl_{:.2f}.png".format(name, resscale, cfl,))

# %% [markdown]
# Save it to disk so that it can be examined with other visualization software (e.g. [Paraview](https://www.paraview.org/)).

# %%
filename = output_folder / "{}_td_solution_resscale_{:.2f}_cfl_{:.2f}.bp".format(name, resscale, cfl,)
with df.io.VTXWriter(sz.mesh.comm, filename, [sz.T_i, sz.vs_i, sz.vw_i]) as vtx:
    vtx.write(0.0)
# zip the .bp folder so that it can be downloaded from jupyter lab
shutil.make_archive(str(filename), 'zip', root_dir=str(filename.parent), base_dir=str(filename.name))

# %% [markdown]
# ### Plot slab temperatures and save slabpaths over time

# %%
# set up a figure
fig, axs = pl.subplots(1,2)

for d, depth in enumerate([0.0, 7.0]):
    # get some points along the slab
    slab = copy.deepcopy(sz.geom.slab_spline)
    slab.translatenormalandcrop(-depth)
    slabpoints = np.array([[curve.points[0].x, curve.points[0].y, 0.0] for curve in slab.interpcurves])
    cinds, cells = fenics_sz.utils.mesh.get_cell_collisions(slabpoints, sz.mesh)

    for sol in solutions[::5]: # remove [::5] to get them all
        t = sol['t']
        T = sol['T']
        # plot the slab temperatures
        Tslab = T.eval(slabpoints, cells)[:,0]
        axs[d].plot(Tslab, -slabpoints[:,1], label='t = {:.0f} Myr'.format(t))

        mode = 'a'
        if d == 0: mode = 'w'
        with open(output_folder / 'slab_temperatures_{:.0f}.txt'.format(t), mode) as f:
            np.savetxt(f, 
                    np.column_stack((slabpoints[:,0], slabpoints[:,1], np.ones(len(slabpoints[:,1]))*depth, Tslab)), 
                    delimiter=' ')
    
    axs[d].set_xlabel('T ($^\circ$C)')
    axs[d].set_ylabel('z (km)')
    axs[d].set_title('{}km depth into slab'.format(depth,))
    axs[d].legend()
    axs[d].invert_yaxis()


# %%
# intersection of crust and slab
crustpt = sz.geom.slab_spline.intersecty(-7.0)
# intersection of aribtrary x and slab
x = 200
arbpt = sz.geom.slab_spline.intersectx(x)
crustpt[0], crustpt[1], arbpt[0], arbpt[1]

# %%
sz.geom.coast_distance, sz.deltaxcoast

# %%
sz.geom.trench_y, sz.deltaztrench

# %%
x = 135
np.minimum(np.maximum(sz.deltaztrench*(1.0 - x/max(sz.deltaxcoast, np.finfo(float).eps)), 0.0), sz.deltaztrench)

# %%
