#!/usr/bin/env bash

usage()
{
    echo "usage: update_python [-h] "
}

while [ -n "$1" ]; do
    case $1 in
        -h | --help )           usage
                                exit
                                ;;
        * )                     echo "ERROR: Unknown option $1"
                                usage
                                exit 1
                                ;;
    esac
    shift
done

full_path=$(realpath $0)
script_path=$(dirname $full_path)
repo_path=$(dirname $script_path)

for f in `find $repo_path/notebooks -not -path "*/.ipynb_checkpoints/*" -type f -name '*.ipynb'`;
do
  fname=$(basename $f)  # get the filename
  nname=${fname#*_}     # strip any leading index_
  rpath=$(dirname ${f#$repo_path/notebooks/})  # get the relative path
  npath=${rpath#??_}    # strip any leading index_
  # global_suites notebooks are special
  if [[ $npath == global_suites/* ]] ;
  then
    npath=global_suites/${npath#global_suites/*_} # strip intermediate index_
    nname=$fname   # leave the index in the filename
  fi
  npath=$repo_path/python/$npath # make a full path again
  nbase=${nname%.*}   # remove the extension for output (added automatically)
  jupyter nbconvert --NbConvertApp.use_output_suffix=False \
                    --TagRemovePreprocessor.enabled=True \
                    --TagRemovePreprocessor.remove_cell_tags="['main', 'ipy']" \
                    --TemplateExporter.exclude_markdown=True \
                    --TemplateExporter.exclude_input_prompt=True \
                    --TemplateExporter.exclude_output_prompt=True \
                    --NbConvertApp.export_format=script \
                    --FilesWriter.build_directory=$npath \
                    --ClearOutputPreprocessor.enabled=True \
                    --NbConvertApp.output_base=$nbase \
                    $f
done


