name: Publish book

on:
  workflow_dispatch:
  push:
    branches:
      - "release"

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write
  actions: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test-docker-build:
    uses: ./.github/workflows/publish_docker.yml

  run-tests-docker:
    uses: ./.github/workflows/test_stable_docker.yml

  run-tests-conda:
    uses: ./.github/workflows/test_stable_conda.yml

  build-book:
    uses: ./.github/workflows/book_stable.yml

  deploy:
    runs-on: ubuntu-22.04
    needs: [test-docker-build, build-book, run-tests-docker, run-tests-conda]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Download docs artifact
        uses: actions/download-artifact@v7
        with:
          name: webpage
          path: "./public"

      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "./public"

      - name: Deploy coverage report to GH Pages
        id: deployment
        uses: actions/deploy-pages@v5
